site_name: Yến sào ĐẠI LÂM MỘC
site_description: 'Nhà phân phối, cung cấp yến sào sỉ và lẻ chất lượng cao tại Việt Nam'
site_author: 'Trương Xuân Vũ'

theme: 
    name: rtd-dropdown
    # Default settings
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    # Development Settings
    #name: null
    #custom_dir: 'rtd_dropdown/'

repo_url: https://github.com/carolynkish300/mkdocs-rtd-dropdown

nav:
    - Trang chủ: index.md
    - All blogs:
        - Một số tác dụng của yến sào với phụ nữ: user-guide/writing-your-docs.md
        - Tìm hiểu công dụng của yến sào dành cho trẻ em: user-guide/styling-your-docs.md
        - Tìm hiểu các công dụng tuyệt vời của yến sào hiện nay: user-guide/configuration.md
        - Deploying Your Docs: user-guide/deploying-your-docs.md
        - Custom Themes: user-guide/custom-themes.md
        - Plugins: user-guide/plugins.md
    - Liên hệ:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

extra_css:
    - css/extra.css

plugins:
    - search

google_analytics: ['UA-165101248-1', 'yensaodailammoc.readthedocs.io']
